---

- name: Create ingress folder
  ansible.builtin.file:
    path: "{{ dfld_dir }}/ingress"
    owner: "{{ dfld_user_info.uid }}"
    group: "{{ dfld_user_info.group }}"
    state: directory
    mode: '0755'  

- name: Copy env file to default location
  ansible.builtin.copy:
    content: "{{ lookup('template', playbook_dir ~ '/templates/container/compose.env.j2') }}"
    dest: "{{ dfld_dir }}/ingress/compose.env"
    owner: "{{ dfld_user_info.uid }}"
    group: "{{ dfld_user_info.group }}"
    mode: '0644'

- name: Read infrastructure yml compose file
  ansible.builtin.set_fact:
    compose_yaml: "{{ lookup('template', playbook_dir ~ '/templates/container/ingress-compose.yml.j2') | from_yaml }}"

- name: Write docker compose file for ingress
  ansible.builtin.copy:  
    content: "{{ compose_yaml | to_nice_yaml }}"
    dest: "{{ dfld_dir }}/ingress/docker-compose.yml"
    owner: "{{ dfld_user_info.uid }}"
    group: "{{ dfld_user_info.group }}"
    mode: '0644'  

- name: Start ingress stack with docker compose
  ansible.builtin.command:
    cmd: docker compose --env-file compose.env up -d
    chdir: "{{ dfld_dir }}/ingress"
  environment:
    COMPOSE_FILE: "{{ dfld_dir }}/ingress/docker-compose.yml"
    COMPOSE_PROJECT_NAME: "ingress"
  args:
    creates: "{{ dfld_dir }}/ingress/.stack_initialized"

