---

- name: Include container specific tasks
  ansible.builtin.include_tasks: "{{ item }}.yml"
  loop:
    - mqtt

- name: Create infrastructure folder
  ansible.builtin.file:
    path: "{{ dfld_dir }}/infrastructure"
    owner: "{{ dfld_user_info.uid }}"
    group: "{{ dfld_user_info.group }}"
    state: directory
    mode: '0755'

- name: Copy env file to default location
  ansible.builtin.copy:
    content: "{{ lookup('template', playbook_dir ~ '/templates/container/compose.env.j2') }}"
    dest: "{{ dfld_dir }}/infrastructure/compose.env"
    owner: "{{ dfld_user_info.uid }}"
    group: "{{ dfld_user_info.group }}"
    mode: '0644'

- name: Read infrastructure yml compose file
  ansible.builtin.set_fact:
    compose_yaml: "{{ lookup('template', playbook_dir ~ '/templates/container/infrastructure-core-compose.yml.j2') | from_yaml }}"

- name: Write docker compose file for core infrastructure
  ansible.builtin.copy:  
    content: "{{ compose_yaml | to_nice_yaml }}"
    dest: "{{ dfld_dir }}/infrastructure/docker-compose.yml"
    owner: "{{ dfld_user_info.uid }}"
    group: "{{ dfld_user_info.group }}"
    mode: '0644'

- name: Start infrastructure stack with docker compose
  ansible.builtin.command:
    cmd: docker compose --env-file compose.env up -d
    chdir: "{{ dfld_dir }}/infrastructure"
  become_user: "{{ dfld_user }}"
  environment:
    COMPOSE_FILE: "{{ dfld_dir }}/infrastructure/docker-compose.yml"
    COMPOSE_PROJECT_NAME: "infrastructure"
  args:
    creates: "{{ dfld_dir }}/infrastructure/.stack_initialized"
